### ISSUE TITLE
Conflicting Return Type in the Calculator.h and CloneInterface.h

### ISSUE THREAD

**Issue by njh80** [qcscine/utilities#7]
Dear Reiher Group,

I've been bootstrapping a puffin for the minimal example of Chemoton but for some reason I've gotten a compile error for the UtilsOS install. There seems to be conflicting uses of the name `cloneImpl()` in the .h files which are private methods which is confusing. I guess this is a problem for my OS so packages are at the bottom. The error occurs even when -std=c++17 is specified

The only CMake warnings were regarding libgomp.so.1 conflicts

`In file included from /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/CalculatorBasics/TestCalculator.h:15:0,
                 from /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/CalculatorBasics/TestCalculator.cpp:8:
/rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/Technical/CloneInterface.h: In instantiation of 'class Scine::Utils::CloneInterface<Scine::Utils::TestCalculator, Scine::Core::Calculator>':
/rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/CalculatorBasics/TestCalculator.h:45:94:   required from here
/rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/Technical/CloneInterface.h:64:30: error: conflicting return type specified for 'std::shared_ptr<Interface> Scine::Utils::CloneInterface<Derived, Base, Interface>::cloneImpl() const [with Derived = Scine::Utils::TestCalculator; Base = Scine::Core::Calculator; Interface = Scine::Core::Calculator]'
   std::shared_ptr<Interface> cloneImpl() const override {
                              ^~~~~~~~~
In file included from /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/CalculatorBasics/TestCalculator.h:10:0,
                 from /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/CalculatorBasics/TestCalculator.cpp:8:
/home/njh80/modulesSource/miniforge3/envs/chemoton/include/Scine/Core/Interfaces/Calculator.h:125:29: error:   overriding 'virtual Scine::Core::Calculator* Scine::Core::Calculator::cloneImpl() const'
   virtual Core::Calculator* cloneImpl() const = 0;
                             ^~~~~~~~~
In file included from /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/CalculatorBasics/TestCalculator.cpp:8:0:
/rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/CalculatorBasics/TestCalculator.h:82:8: error: 'bool Scine::Utils::TestCalculator::allowsPythonGILRelease() const' marked 'override', but does not override
   bool allowsPythonGILRelease() const override {
        ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/Utils/CMakeFiles/UtilsOS.dir/Utils/CalculatorBasics/TestCalculator.cpp.o] Error 1
make[1]: *** [src/Utils/CMakeFiles/UtilsOS.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/site-packages/scine_puffin/__main__.py", line 148, in <module>
    main()
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/site-packages/scine_puffin/__main__.py", line 134, in main
    main_bootstrap(config)
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/site-packages/scine_puffin/__main__.py", line 73, in main_bootstrap
    bootstrap(config)
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/site-packages/scine_puffin/bootstrap.py", line 72, in bootstrap
    utils.install(utils_build_dir, install_dir, config["resources"]["cores"])
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/site-packages/scine_puffin/programs/utils.py", line 22, in install
    self.scine_module_install(repo_dir, install_dir, ncores)
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/site-packages/scine_puffin/programs/program.py", line 162, in scine_module_install
    subprocess.run(["make", "-j" + str(ncores), "install"], env=env, check=True)
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', '-j1', 'install']' returned non-zero exit status 2.`

Modules:
Python 3.8.18 (venv via Conda)
RedHat CentOS7
GCC 7.4.0
Eigen 3.3.5
CMake 3.17
Boost 1.78.0
(MongoDB 7.0.2)

**Comment by njh80** [comment]
Sure thing, I've changed the extension to .log to allow posting to GitHub:
[Calculator.log](https://github.com/qcscine/utilities/files/13886756/Calculator.log)

I've completely deleted the folder /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/ and rebuilt via `git clone` and the same error comes up. Are the live repositories incompatible? 

Here is the full output:

python3 -m scine_puffin -c puffin.yaml bootstrap
Loading configuration: puffin.yaml
Applying environment variables afterwards.

+-----------------+
|  Bootstrapping  |
+-----------------+

Getting Puffin ready for use.


Building SCINE Core/Utils from sources.

-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/local/software/archive/linux-scientific7-x86_64/gcc-9/gcc-7.4.0-rsjxbfcfe4paorgplbrt6wnnvxvs7dl6/bin/gcc
-- Check for working C compiler: /usr/local/software/archive/linux-scientific7-x86_64/gcc-9/gcc-7.4.0-rsjxbfcfe4paorgplbrt6wnnvxvs7dl6/bin/gcc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/software/archive/linux-scientific7-x86_64/gcc-9/gcc-7.4.0-rsjxbfcfe4paorgplbrt6wnnvxvs7dl6/bin/g++
-- Check for working CXX compiler: /usr/local/software/archive/linux-scientific7-x86_64/gcc-9/gcc-7.4.0-rsjxbfcfe4paorgplbrt6wnnvxvs7dl6/bin/g++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /home/njh80/modulesSource/miniforge3/envs/chemoton/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found version "1.78.0") found components: system filesystem 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_EXECUTABLE


-- Build files have been written to: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/core/build
Scanning dependencies of target Core
[ 50%] Building CXX object src/Core/CMakeFiles/Core.dir/Core/ModuleManager.cpp.o
[100%] Linking CXX shared library libcore.so
[100%] Built target Core
Install the project...
-- Install configuration: "Release"
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/Log.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/Interfaces
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/Interfaces/ObjectWithOrbitals.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/Interfaces/Calculator.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/Interfaces/CalculatorWithReference.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/Interfaces/WavefunctionOutputGenerator.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/Interfaces/EmbeddingCalculator.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/Interfaces/MMParametrizer.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/ModuleManager.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/ExportControl.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/DerivedModule.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/Module.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/Exceptions.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/BaseClasses
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/BaseClasses/ObjectWithLog.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/BaseClasses/ObjectWithStructure.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/include/Scine/Core/BaseClasses/StateHandableObject.h
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/lib/libcore.so
-- Set runtime path of "/rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/lib/libcore.so" to ""
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/lib/cmake/ScineCore/ScineCoreConfig.cmake
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/lib/cmake/ScineCore/ScineCoreConfigVersion.cmake
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/lib/cmake/ScineCore/ScineCoreTargets.cmake
-- Installing: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/install/lib/cmake/ScineCore/ScineCoreTargets-release.cmake
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/local/software/archive/linux-scientific7-x86_64/gcc-9/gcc-7.4.0-rsjxbfcfe4paorgplbrt6wnnvxvs7dl6/bin/gcc
-- Check for working C compiler: /usr/local/software/archive/linux-scientific7-x86_64/gcc-9/gcc-7.4.0-rsjxbfcfe4paorgplbrt6wnnvxvs7dl6/bin/gcc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/software/archive/linux-scientific7-x86_64/gcc-9/gcc-7.4.0-rsjxbfcfe4paorgplbrt6wnnvxvs7dl6/bin/g++
-- Check for working CXX compiler: /usr/local/software/archive/linux-scientific7-x86_64/gcc-9/gcc-7.4.0-rsjxbfcfe4paorgplbrt6wnnvxvs7dl6/bin/g++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Scine::Core found locally at /home/njh80/modulesSource/miniforge3/envs/chemoton/lib/cmake/ScineCore
-- Found package yaml-cpp at /home/njh80/modulesSource/miniforge3/envs/chemoton/share/cmake/yaml-cpp
Cloning into 'lbfgspp-src'...
Note: switching to 'v0.2.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 00f0f1b fix version number
-- Performing Test WALL_SUPPORTED
-- Performing Test WALL_SUPPORTED - Success
-- Eigen3 version: 3.3.5
-- LBFGSB was not found in your PATH, so it was downloaded.
Cloning into 'spglib-src'...
Note: switching to '9458171a2eb9bea9036632a408da7b269ea07bbb'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 9458171 Merge pull request #191 from steinmig/avoid-odr-problems
-- spglib was not found in your PATH, so it was downloaded.
-- Found MKL: /usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linux/mkl/include  
-- Found Intel MKL libraries:
-- /usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linux/mkl/include 
-- /usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linux/mkl/lib/intel64/libmkl_avx2.so 
-- /usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linux/mkl/lib/intel64/libmkl_vml_avx2.so 
-- /usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linux/mkl/lib/intel64/libmkl_core.so 
-- /usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linux/mkl/lib/intel64/libmkl_intel_lp64.so 
-- /usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linux/mkl/lib/intel64/libmkl_gnu_thread.so 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found MKL for use with Eigen3
-- GTest and GMock were not found in your PATH, they are being downloaded.
Cloning into 'googletest-src'...
Note: switching to 'release-1.10.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 703bd9ca Googletest export
-- Found PythonInterp: /home/njh80/modulesSource/miniforge3/envs/chemoton/bin/python3 (found version "3.8.18") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- GTest and GMock sources were downloaded.
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
Cloning into 'pybind11-src'...
Note: switching to 'v2.10.4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 5b0a6fc2 chore: bump version to 3.10.4
-- pybind11 v2.10.4 
-- Found PythonInterp: /home/njh80/modulesSource/miniforge3/envs/chemoton/bin/python3 (found suitable version "3.8.18", minimum required is "3.6") 
-- Found PythonLibs: /home/njh80/modulesSource/miniforge3/envs/chemoton/lib/libpython3.8.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Pybind11 was not found in your PATH, so it was downloaded.
-- Targets to copy for python bindings: Scine::Core;Scine::UtilsOS
-- Could NOT find PY_pybind11_stubgen (missing: PY_PYBIND11_STUBGEN) 
-- Not generating typechecking stubs for python package as pybind11-stubgen was not found
-- Found PY_sphinx: /home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/site-packages/sphinx  
-- Configuring done
CMake Warning at src/Utils/CMakeLists.txt:37 (add_library):
  Cannot generate a safe runtime search path for target UtilsOS because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libgomp.so.1] in /usr/local/software/master/gcc/7/lib64 may be hidden by files in:
      /home/njh80/modulesSource/miniforge3/envs/chemoton/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/Utils/CMakeLists.txt:81 (add_library):
  Cannot generate a safe runtime search path for target UtilsOSModule because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libgomp.so.1] in /usr/local/software/master/gcc/7/lib64 may be hidden by files in:
      /home/njh80/modulesSource/miniforge3/envs/chemoton/lib

  Some of these libraries may not be found correctly.


CMake Warning at build/pybind11-src/tools/pybind11Tools.cmake:177 (add_library):
  Cannot generate a safe runtime search path for target scine_utilities
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libgomp.so.1] in /usr/local/software/master/gcc/7/lib64 may be hidden by files in:
      /home/njh80/modulesSource/miniforge3/envs/chemoton/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  src/Utils/CMakeLists.txt:153 (pybind11_add_module)


-- Generating done
-- Build files have been written to: /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/build
Scanning dependencies of target symspg_objects
[  0%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/arithmetic.c.o
[  0%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/cell.c.o
[  1%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/debug.c.o
[  1%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/delaunay.c.o
[  1%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/determination.c.o
[  2%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/hall_symbol.c.o
[  2%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/kgrid.c.o
[  2%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/kpoint.c.o
[  3%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/magnetic_spacegroup.c.o
[  3%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/mathfunc.c.o
[  3%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/msg_database.c.o
[  4%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/niggli.c.o
[  4%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/overlap.c.o
[  4%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/pointgroup.c.o
[  5%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/primitive.c.o
[  5%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/refinement.c.o
[  5%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/site_symmetry.c.o
[  6%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/sitesym_database.c.o
[  6%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/spacegroup.c.o
[  6%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/spg_database.c.o
[  7%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/spglib.c.o
[  7%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/spin.c.o
[  8%] Building C object src/Utils/CMakeFiles/symspg_objects.dir/__/__/spglib-src/src/symmetry.c.o
[  8%] Built target symspg_objects
Scanning dependencies of target UtilsOS
[  8%] Building CXX object src/Utils/CMakeFiles/UtilsOS.dir/Utils/Bonds/BondDetector.cpp.o
[  8%] Building CXX object src/Utils/CMakeFiles/UtilsOS.dir/Utils/Bonds/BondDetectorRadii.cpp.o
[  9%] Building CXX object src/Utils/CMakeFiles/UtilsOS.dir/Utils/Bonds/SolidStateBondDetector.cpp.o
[  9%] Building CXX object src/Utils/CMakeFiles/UtilsOS.dir/Utils/Bonds/VanDerWaalsBondDetector.cpp.o
[  9%] Building CXX object src/Utils/CMakeFiles/UtilsOS.dir/Utils/CalculatorBasics/Results.cpp.o
[ 10%] Building CXX object src/Utils/CMakeFiles/UtilsOS.dir/Utils/CalculatorBasics/ResultsAutoCompleter.cpp.o
[ 10%] Building CXX object src/Utils/CMakeFiles/UtilsOS.dir/Utils/CalculatorBasics/StatesHandler.cpp.o
[ 10%] Building CXX object src/Utils/CMakeFiles/UtilsOS.dir/Utils/CalculatorBasics/TestCalculator.cpp.o
In file included from /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/CalculatorBasics/TestCalculator.h:15:0,
                 from /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/CalculatorBasics/TestCalculator.cpp:8:
/rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/Technical/CloneInterface.h: In instantiation of 'class Scine::Utils::CloneInterface<Scine::Utils::TestCalculator, Scine::Core::Calculator>':
/rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/CalculatorBasics/TestCalculator.h:45:94:   required from here
/rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/Technical/CloneInterface.h:64:30: error: conflicting return type specified for 'std::shared_ptr<Interface> Scine::Utils::CloneInterface<Derived, Base, Interface>::cloneImpl() const [with Derived = Scine::Utils::TestCalculator; Base = Scine::Core::Calculator; Interface = Scine::Core::Calculator]'
   std::shared_ptr<Interface> cloneImpl() const override {
                              ^~~~~~~~~
In file included from /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/CalculatorBasics/TestCalculator.h:10:0,
                 from /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/CalculatorBasics/TestCalculator.cpp:8:
/home/njh80/modulesSource/miniforge3/envs/chemoton/include/Scine/Core/Interfaces/Calculator.h:125:29: error:   overriding 'virtual Scine::Core::Calculator* Scine::Core::Calculator::cloneImpl() const'
   virtual Core::Calculator* cloneImpl() const = 0;
                             ^~~~~~~~~
In file included from /rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/CalculatorBasics/TestCalculator.cpp:8:0:
/rds-d7/user/njh80/hpc-work/chemoton-conda/puffin/software/build/utils/src/Utils/Utils/CalculatorBasics/TestCalculator.h:82:8: error: 'bool Scine::Utils::TestCalculator::allowsPythonGILRelease() const' marked 'override', but does not override
   bool allowsPythonGILRelease() const override {
        ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/Utils/CMakeFiles/UtilsOS.dir/Utils/CalculatorBasics/TestCalculator.cpp.o] Error 1
make[1]: *** [src/Utils/CMakeFiles/UtilsOS.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/site-packages/scine_puffin/__main__.py", line 148, in <module>
    main()
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/site-packages/scine_puffin/__main__.py", line 134, in main
    main_bootstrap(config)
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/site-packages/scine_puffin/__main__.py", line 73, in main_bootstrap
    bootstrap(config)
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/site-packages/scine_puffin/bootstrap.py", line 72, in bootstrap
    utils.install(utils_build_dir, install_dir, config["resources"]["cores"])
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/site-packages/scine_puffin/programs/utils.py", line 22, in install
    self.scine_module_install(repo_dir, install_dir, ncores)
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/site-packages/scine_puffin/programs/program.py", line 162, in scine_module_install
    subprocess.run(["make", "-j" + str(ncores), "install"], env=env, check=True)
  File "/home/njh80/modulesSource/miniforge3/envs/chemoton/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', '-j1', 'install']' returned non-zero exit status 2.

**Comment by steinmig** [comment]
Thanks!
As suspected the problem is an existing installation of Core that Utilities picks up as indicated in the CMake of Utils with the line:

` -- Scine::Core found locally at /home/njh80/modulesSource/miniforge3/envs/chemoton/lib/cmake/ScineCore`

You can either delete this environment or folders if you don't need it anymore or remove them from your `LD_LIBRARY_PATH` and `CMAKE_PREFIX_PATH` environment variables in the terminal you are bootstrapping the Puffin in.

**Comment by steinmig** [comment]
Glad it worked!
Yes, to my knowledge the conda forge packages are not official and we release only on PyPI
